name: CI

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci

  lint:
    needs: install
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci

    - run: npm run lint

  unit-test:
    needs: install
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci

    - run: npm run test
      env:
        CI: true

  build:
    needs: install
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci

    - run: npm run build
